from .basic_data_inspection import DataInspector, DataTypesInspection, SummaryStatsInspection
from .missing_values_analysis import MissingValueAnalyser
from .univariate_analysis import UnivariateAnalyser, NumericalUnivariateAnalysis, CategoricalUnivariateAnalysis
from .bivariate_analysis import BivariateAnalyser, NumericalvsNumeriacalAnalysis, CategoricalvsNumericalAnalysis
from .multivariate_analysis import MultiVariateAnalyser